apiVersion: apps/v1
kind: Deployment
metadata:
  name: apk1
  labels:
    app: frontend
spec:
  replicas: 3  # Fixed typo
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: apk
          image: mdirshaq/demo-test:latest
          ports:
            - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
